### PR TITLE
ISSUE-67 Schema registry UI is very slow at initial load

### PR DESCRIPTION
**Pull request by shahsank3t**

### CODE REVIEW

**Comment by shahsank3t** [comment]
@satishd This PR is dependent on https://github.com/hortonworks/registry/pull/71 and has UI changes for that PR too.

**Comment by satishd** [comment]
@shahsank3t #71 is merged and you can rebase this PR.

**Comment by shahsank3t** [comment]
@satishd rebased PR

**Comment by harshach** [comment]
+1

**Pull request merged**
