### PR TITLE
ISSUE-117 Added aggregate APIs for schema metadata

### LINKED ISSUE #117: API for aggregated information about schemametadata
Aggregated information for schema metadata including
- include versions of schema
- any custom ser/des configured

### PR DESCRIPTION
**Pull request by satishd**
Respective REST APIs are added below.
- GET api/v1/schemaregistry/schemas/aggregated
- GET api/v1/schemaregistry/schemas/{name}/aggregated

Closes #117

### CODE REVIEW

**Comment by satishd** [comment]
@shahsank3t You can look at the APIs mentioned in the above comment in swagger for more details.

**Comment by shahsank3t** [comment]
@satishd Thanks, I'll look into it and make appropriate UI changes.

**Comment by satishd** [comment]
@shahsank3t With this change, modified API for GET /schemas/ now returns the below structure, you need to make respective changes in UI.
```
{
  "entities": [
    {
      "schemaMetadata": {
        "type": "avro",
        "schemaGroup": "Kafka",
        "name": "foo",
        "description": null,
        "compatibility": "BACKWARD",
        "evolve": true
      },
      "id": 1,
      "timestamp": 1495198546954
    }
  ]
}

```

**Comment by shahsank3t** [comment]
+1 This API helps saving numeros API calls. Thanks @satishd

**Pull request merged**
