### PR TITLE
Fix for Issue #298

### PR DESCRIPTION
**Pull request by enoren**
Not sure what branch you guys would want to put this on, but since we are working with 0.3.0 I based it on what I believe the commit is for that. As an aside, it appears that the v0.3.0 tag is incorrectly set on master instead of the 0.3.0 branch which I think is referenced in https://groups.google.com/forum/#!topic/registry/8GMrLlmhsic however maybe the tag fix was never pushed up?

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@enoren pr should be to master

**Comment by satishd** [comment]
@enoren,
No maint releases planned for 0.3.0, can you raise PR against master as @michaelandrepearce mentioned in earlier comment?

**Comment by enoren** [comment]
Unfortunately it looks like changing the base didn't work for free so I will have to create a new PR based off of master when I get a chance.

Thanks

**Comment by satishd** [comment]
@enoren Create a new branch forked from `master`, make the change you mentioned in #298 and raise PR with that branch.

**Comment by enoren** [comment]
New PR https://github.com/hortonworks/registry/pull/303

**Pull request closed without merging**
