### PR TITLE
ISSUE-120: Add documentation for migration

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Initial work for addending migration documentation.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@satishd it was my first encounter with rst, i assumed it was like markdown, so used my ide's markdown editor. Is there any recommended IntelliJ plugin for RST editing, or even stand alone tool that you suggest?

**Comment by satishd** [comment]
@michaelandrepearce same here :) Intellij identifies rST but it does not show any view mode. I was using http://rst.ninjs.org/ tool

**Comment by michaelandrepearce** [comment]
@satishd thanks, that tool was useful, updated and pushed. 
Will need updating later with links to maybe further docs about schema import once sorted.
But for now i think its good.

**Comment by satishd** [comment]
Closes #120

**Pull request merged**
