### PR TITLE
[CSP-528] Replace license headers in SR source files

### PR DESCRIPTION
**Pull request by csengevirag**
All source code headers altered from Hortonworks to Cloudera in 514 files.

### CODE REVIEW

**Comment by guruchai** [comment]
LGTM...
- Source code does not seem to have been touched.
- Hortonworks is replaced with Cloudera in all the licence files.

@caseyvalk , @csengevirag Please check if NOTICE.txt requires changes as well.

**Comment by raju-saravanan** [comment]
@caseyvalk Can you please let us know if you are ok with the changes in this PR. If so I can go ahead and merge it.

**Comment by caseyvalk** [comment]
Hi, what changes specifically?  I don't know what I am looking at.

Thanks,
Casey
*Cassandra L. Valk* | Open Source License Analyst / Sr. Contracts Manager
t. (949) 201-3201

NOTICE: Prepared by a member of the Cloudera legal team. This message and any
attachments may contain confidential and/or privileged information of Cloudera,
Inc. and/or its affiliates. If you have received this communication in
error, please advise the sender by reply email and immediately delete this
message and any attachments without copying, reviewing, or disclosing the
contents. Thank you for your cooperation.

**Comment by gergowilder** [comment]
> @caseyvalk Can you please let us know if you are ok with the changes in this PR. If so I can go ahead and merge it.

@raju-saravanan I reviewed the PR with @caseyvalk and she approved it. Please merge the change.

**Comment by raju-saravanan** [comment]
@gergowilder : Thanks, Gergo. I will merge the PR.

**Pull request merged**
