### PR TITLE
ISSUE-70: Order by implementation support for select queries

### PR DESCRIPTION
**Pull request by satishd**

### CODE REVIEW

**Comment by satishd** [comment]
@shahsank3t Can you try this out from UI while listing out schema-metadatas?
URL format is: 
```http://<registry-url>/api/v1/schemaregistry/schemas/?_orderByFields=<field-name-1>,<a/d>,<field-name-2>,<a/d>```
_orderByfFields parama value should have the sequence of fields in which respective ordering is done.
a - ascending
d- descending

For ex:
```http://localhost:9090/api/v1/schemaregistry/schemas/?_orderByFields=timestamp,d```
Above API returns results sorted by timestamp field in descending order

**Comment by shahsank3t** [comment]
@satishd I am getting the error on hitting API http://localhost:9090/api/v1/schemaregistry/schemas/?_orderByFields=timestamp,d

```
{
  responseCode: 1102,
  responseMessage: "An exception with message [com.hortonworks.registries.schemaregistry.SchemaVersionStorable cannot be cast to com.hortonworks.registries.schemaregistry.SchemaMetadataStorable] was thrown while processing request."
}
```

**Comment by satishd** [comment]
@shahsank3t Missed a change in earlier PR, Can you try now?

**Comment by shahsank3t** [comment]
+1 tested and verified the response

**Comment by satishd** [comment]
@shahsank3t Let me know if you want to make UI changes as part of this PR else I will merge it.

**Comment by shahsank3t** [comment]
@satishd I will make UI changes as part of https://github.com/hortonworks/registry/issues/67. So you can go ahead and merge this one.

**Pull request merged**
