### PR TITLE
ISSUE-132 Allow customising key/value suffix by configuration

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Improve on https://github.com/hortonworks/registry/issues/99
Make the suffix configurable, as such reducing the need for custom concrete extensions of the serializer.

### CODE REVIEW

**Comment by satishd** [comment]
@michaelandrepearce Do you use prefix/suffix for schema names in your scenarios?

**Comment by satishd** [comment]
Closes #132

**Comment by satishd** [comment]
@michaelandrepearce We are following PR description and commits to start with respective issue  like "ISSUE-XXX <message>"
I will take care of the current PRs and commits for now, you can follow this convention for next PRs.

**Comment by michaelandrepearce** [comment]
@satishd sure. re use case, it was actually inline with the general work I'm trying to make migration / integration from confluent easier. In confluent they use -key and -value suffix's. 

So this paired with the confluent api, and then the protocol changes would mean you could inter-op where people have confluent serdes without changing code, just can redirect the schema registry url.

**Pull request closed without merging**
