### PR TITLE
ISSUE-242 Added schema version lifecycle statemachine APIs for users …

### PR DESCRIPTION
**Pull request by satishd**
- Added schema version lifecycle statemachine APIs for users to add any custom states.
 - Added APIs required for clients including UI to get statemachine information and transition APIs.
 - Changed details column type to blob in schema_version_state table which gives mroe freedom to put whatever content by custom state implementors.

### CODE REVIEW

**Comment by satishd** [comment]
closes #242

**Comment by satishd** [comment]
@shahsank3t Can you try the APIs mentioned in PR note and put your comments?

**Comment by shahsank3t** [comment]
@satishd 
I am getting duplicate entries in `transitions` array for statemachine API.
Could you please verify if it's actually a bug or maybe just something I messed up on my local.

**Comment by satishd** [comment]
@shahsank3t Nice finding! Pushed a fix for that. Let me know if you are fine with the APIs so that this can be merged.

**Pull request merged**
