### PR TITLE
Option to configure security in Schema Registry cluster provided.

### PR DESCRIPTION
**Pull request by kamalcph**
While running the registry cluster in docker, we can specify whether to enable / disable the Kerberos authentication.

### CODE REVIEW

**Comment by kamalcph** [comment]
@priyank5485 

I'm facing the below the error in registry docker after the addition of JWT. How to resolve it ?

```
ERROR [2018-03-20 12:01:43,327] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.IllegalArgumentException: Illegal base64 character 3c
! at java.util.Base64$Decoder.decode0(Base64.java:714)
! at java.util.Base64$Decoder.decode(Base64.java:526)
! at sun.security.util.Pem.decode(Pem.java:47)
! ... 48 common frames omitted
! Causing: java.io.IOException: java.lang.IllegalArgumentException: Illegal base64 character 3c
! at sun.security.util.Pem.decode(Pem.java:49)
! at sun.security.provider.X509Factory.readOneBlock(X509Factory.java:638)
! at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:96)
! ... 46 common frames omitted
! Causing: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: java.lang.IllegalArgumentException: Illegal base64 characte
r 3c
! at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:110)
! at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
! at com.hortonworks.registries.auth.util.CertificateUtil.parseRSAPublicKey(CertificateUtil.java:50)
! ... 44 common frames omitted
! Causing: javax.servlet.ServletException: CertificateException - PEM may be corrupt
! at com.hortonworks.registries.auth.util.CertificateUtil.parseRSAPublicKey(CertificateUtil.java:60)
! at com.hortonworks.registries.auth.server.JWTAuthenticationHandler.init(JWTAuthenticationHandler.java:128)
! at com.hortonworks.registries.auth.server.AuthenticationFilter.initializeAuthHandler(AuthenticationFilter.java:238)
! at com.hortonworks.registries.auth.server.AuthenticationFilter.init(AuthenticationFilter.java:224)
! at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:137)
! at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:856)
! at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
! at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
! at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
! at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:103)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:231)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
! at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:252)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
! at org.eclipse.jetty.server.Server.start(Server.java:411)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
! at org.eclipse.jetty.server.Server.doStart(Server.java:378)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:75)
! at io.dropwizard.Application.run(Application.java:79)
! at com.hortonworks.registries.webservice.RegistryApplication.main(RegistryApplication.java:296)
```

**Comment by priyank5485** [comment]
@kamalcph What value are you using for public.key.pem property? It is supposed to be the PEM encoded public key of the issuer of the token.

**Comment by priyank5485** [comment]
Looked more at your code. It seems that you will need to create and export a X509 certificate so you can use it as a value in that config.

**Comment by priyank5485** [comment]
@kamalcph Can you try the below for now? It is the public key corresponding to knox user guide described at https://knox.apache.org/books/knox-1-0-0/user-guide.html

public.key.pem: "MIICOjCCAaOgAwIBAgIJAKrtfJWiceB9MA0GCSqGSIb3DQEBBQUAMF8xCzAJBgNVBAYTAlVTMQ0w
CwYDVQQIEwRUZXN0MQ0wCwYDVQQHEwRUZXN0MQ8wDQYDVQQKEwZIYWRvb3AxDTALBgNVBAsTBFRl
c3QxEjAQBgNVBAMTCWxvY2FsaG9zdDAeFw0xODAyMjcwMTQzNDVaFw0xOTAyMjcwMTQzNDVaMF8x
CzAJBgNVBAYTAlVTMQ0wCwYDVQQIEwRUZXN0MQ0wCwYDVQQHEwRUZXN0MQ8wDQYDVQQKEwZIYWRv
b3AxDTALBgNVBAsTBFRlc3QxEjAQBgNVBAMTCWxvY2FsaG9zdDCBnzANBgkqhkiG9w0BAQEFAAOB
jQAwgYkCgYEAmMBzZPp7RI6kzVDf3PTLrVIFdQxN+Li5Ve+H2NXDul5ldy9R2BlrDOf6BJQbzBfn
Tt88Ldnv/R0BOsIwu88enqbDAryzMRvG3fsgc+6m48Hv7EtJ2QGn1moLL4KI16DNZzGKTrrfHs1I
ACfC4VI+S9mtlN+629ORv56XZVCe0u0CAwEAATANBgkqhkiG9w0BAQUFAAOBgQABRUTQz+BZlqj0
KyadfQE7nhi5A/FmRRjtqXqQ+Xforol0ZJjgf0mbtD81K0toS5S1gikHrCdif0Au8F88Q+xktllp
ulcwsgsY86Xwo22ge72RLpLcIBsWj8JztfVKgSfqE/SWIU4Ok4CcjVvdu8LOkKRHnsO1/zlx57tx
Mf2qLw=="

**Comment by kamalcph** [comment]
@priyank5485 

As of now, I have disabled the JWT KNOX SSO Authentication. Thanks for your guidance.

**Pull request closed without merging**
