### PR TITLE
ISSUE-99: Kafka avro serializer/deserializer should treat schema name as topic name by default

### PR DESCRIPTION
**Pull request by satishd**

### CODE REVIEW

**Comment by harshach** [comment]
@satishd do we throw a error if the user registered lets say "truck_events" and now tries to register a "truck_events:v" , vice versa

**Comment by satishd** [comment]
@harshach We do not throw an error in those scenarios.

**Comment by satishd** [comment]
@harshach No error is thrown, default implementation maps schema name as topic name for values. This can be over ridden by user extending `KafkaAvroSerializer`.  This is to keep this contract simple. Respective changes in streamline are done once this PR is merged.

**Comment by harshach** [comment]
+1

**Pull request merged**
