### PR TITLE
ISSUE-543 Fix broken json format in Schema.Field when it's used as nested - introduced in Jackson 2.9

### LINKED ISSUE #543: Fix broken json format in Schema.Field when it's used as nested - introduced in Jackson 2.9
Below simple test fails:

```
@Test
    public void testSerializeNestedSchema() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        Schema nested = new Schema();
        Schema.Field f1 = new Schema.Field("field1", Type.INTEGER);
        Schema.Field x = new Schema.Field("x", Type.INTEGER);
        Schema.Field y = new Schema.Field("y", Type.INTEGER);
        Schema.Field f2 = Schema.NestedField.of("field2", Arrays.asList(x, y));
        nested.setFields(Arrays.asList(f1, f2));
        String expected = "{\"fields\":[{\"name\":\"field1\",\"type\":\"INTEGER\",\"optional\":false}," +
                "{\"name\":\"field2\",\"type\":\"NESTED\",\"optional\":false,\"fields\":[{\"name\":\"x\",\"type\":\"INTEGER\"," +
                "\"optional\":false},{\"name\":\"y\",\"type\":\"INTEGER\",\"optional\":false}]}]}";
        assertEquals(expected, mapper.writeValueAsString(nested));
        Schema schema2;
        schema2 = mapper.readValue(expected, Schema.class);
        assertEquals(nested, schema2);
    }
```

```
Expected :{"fields":[{"name":"field1","type":"INTEGER","optional":false},{"name":"field2","type":"NESTED","optional":false,"fields":[{"name":"x","type":"INTEGER","optional":false},{"name":"y","type":"INTEGER","optional":false}]}]}
Actual   :{"fields":[{"type":"null","name":"field1","type":"INTEGER","optional":false},{"type":"null","name":"field2","type":"NESTED","optional":false,"fields":[{"type":"null","name":"x","type":"INTEGER","optional":false},{"type":"null","name":"y","type":"INTEGER","optional":false}]}]}
```

This looks like due to upgrade to jackson from 2.7.x to 2.9.x, according to this comment:
https://github.com/hortonworks/registry/pull/542#issuecomment-469628614

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* also add test which doesn't make sense for Streamline to have

Closes #543

### CODE REVIEW

**Comment by satishd** [comment]
@raju-saravanan Can you review and verify this change? @HeartSaVioR and I are not sure whether `AbstractStateDetails` will have any impact on this change.

**Comment by HeartSaVioR** [comment]
@satishd 
> @HeartSaVioR and I are not sure whether AbstractStateDetails will have any impact on this change.

More clearly, the patch itself is OK. I'm wondering AbstractStateDetails also needs to change the value, but if the 'type' field (property) is not available in implementation of AbstractStateDetails, that should be OK to keep it as it is.

cc. @raju-saravanan

**Comment by arunmahadevan** [comment]
Merged to master

**Comment by HeartSaVioR** [comment]
FYI: also pushed to HDF-3.4.0.0 branch as well, since this patch should be actually along with #542

**Pull request closed without merging**
