### PR TITLE
ISSUE-223 Removing unneeded dependencies for serdes/client modules

### PR DESCRIPTION
**Pull request by satishd**
- Created registry-common-client module which has only the classes required for client
- Added registry-common-client module wherever appropriate

### CODE REVIEW

**Comment by satishd** [comment]
@michaelandrepearce Can you review and verify this from standalone project which does not have any other schema registry dependencies? 

This fix should be part of the next version targeted in next few days.

**Comment by michaelandrepearce** [comment]
@satishd 

These probably should be pulled out the client and serdes poms and added to common instead.

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
        </dependency>

like wise in serdes

bits like should be removed as declared in common-client.
        <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-annotations</artifactId>
          <version>${jackson.version}</version>
        </dependency>

**Comment by satishd** [comment]
@michaelandrepearce Thanks for reviewing. 
Below are already part of schema-registry-common module
```
   <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
        </dependency>
````
Latest commit removes any modules in serdes which are already added as part of schema-registry-common.

**Comment by satishd** [comment]
@michaelandrepearce Did you verify these changes in a standalone project using schema-registry-client or serdes connecting to remote SR server?

**Comment by satishd** [comment]
@michaelandrepearce Can you review the latest changes and also verify by running kafka ser/des or SR client running in a project referring to serdes/client modules?

**Comment by satishd** [comment]
@michaelandrepearce pinging for review the latest changes.

**Comment by michaelandrepearce** [comment]
@satishd +1 lgtm, I’m away atm (2 weeks holiday) so haven’t checked out and run an integration but from visual looks good.

**Comment by satishd** [comment]
@michaelandrepearce Thanks for reviewing.

**Pull request closed without merging**
