### PR TITLE
MINOR: possibility to include mysql-connector jar in final tar.gz

### PR DESCRIPTION
**Pull request by akatona84**
This functionality is tied to `with-mysql-jar` profile

### CODE REVIEW

**Comment by raju-saravanan** [comment]
@akatona84: May I know the motivation behind this ?

**Comment by akatona84** [comment]
> @akatona84: May I know the motivation behind this ?

Yes, it is required for cdp runtime. Libs dir won't be writeable by schemaregistry (otherwise bootstrap would download this jar)

**Comment by raju-saravanan** [comment]
@akatona84: Alright. How will the oracle ojdbc dependencies be dealt with in CDP runtime?

**Comment by akatona84** [comment]
> @akatona84: Alright. How will the oracle ojdbc dependencies be dealt with in CDP runtime?

I think it wasn't provided in csp either. User will copy them in place.

**Pull request merged**
