### PR TITLE
ISSUE-624 : Give executable permissions to all registry scripts

### PR DESCRIPTION
**Pull request by suminb**
I've noticed the following scripts do not have executable permissions.

- bin/registry
- bin/registry-server-start.sh
- bootstrap/bootstrap-storage-initenv.sh
- bootstrap/bootstrap-storage.sh

I would be nice to be able to run these files without manually giving executable permissions.

### CODE REVIEW

**Comment by raju-saravanan** [comment]
Fixes #624

**Comment by raju-saravanan** [comment]
@suminb thanks for the PR. Can you set the same permissions to /conf/registry-env.sh as well ?

**Comment by suminb** [comment]
Done. However, I found other `*.sh` files without executable permissions.

```
$ find . ! -perm -u+x -name "*.sh"
./docker/images/kafka/kafka-service.sh
./docker/images/registry/start-registry.sh
./docker/kdc-registry.sh
./webservice/target/node/node_modules/npm/test/packages/npm-test-ignore/test.sh
./webservice/target/node/node_modules/npm/test/packages/npm-test-files/test.sh
./webservice/target/node/node_modules/npm/scripts/release.sh
./webservice/src/main/resources/node_modules/react-breadcrumbs/demo/surge.sh
./webservice/src/main/resources/node_modules/react-breadcrumbs/demo/run.sh
./webservice/src/main/resources/node_modules/coa/lib/completion.sh
./webservice/src/main/resources/node_modules/sourcemapped-stacktrace/demo/make.sh
./webservice/src/main/resources/node_modules/JSV/jsdoc-toolkit/jsrun.sh
./webservice/src/main/resources/node_modules/object.assign/test.sh
```

I would assume packages under `node_modules` directories are managed by `npm` so we don't have to worry about them. But should we also give executable permissions on script files under the `docker` directory?

**Comment by raju-saravanan** [comment]
@suminb Yeah, the docker scripts need the execute permissions. We don't need to set executable permissions for scripts run by npm.

**Comment by suminb** [comment]
All done.

**Pull request merged**
