### PR TITLE
Kafka Avro Serde

### PR DESCRIPTION
**Pull request by the-ricker**
Added Kafka Avro Serde which is needed for Kafka Streams API, etc.

### CODE REVIEW

**Comment by satishd** [comment]
@the-ricker Thanks for raising this PR. We are tracking PRs with respective Github issues. Good to create an issue for this PR and mention that issue in PR's description and commit message like below.

ISSUE-XXX: <descirption>

**Comment by harshach** [comment]
@the-ricker also can you squash the commits into a single one.

**Comment by michaelandrepearce** [comment]
Why not simply use the kafka serdes class:

org.apache.kafka.common.serialization.Serdes.serdeFrom

or if you want a concrete simply:

public class KafkaSerdes extends Serdes {
    static public final class KafkaAvroSerde extends WrapperSerde<byte[]> {
        public KafkaAvroSerde() {
            super(new KafkaAvroSerializer(), new KafkaAvroSerializer());
        }
    }
}

**Comment by the-ricker** [comment]
That would work. One needs a concrete class to use in third party tools such as Nifi, etc.

**Comment by michaelandrepearce** [comment]
@the-ricker the solution you have as is I'm happy with, its really just implementation styles, and just wanted to highlight the option.

Im +1 your solution.
It be great if you could squash the commits as is, so it can be merged and the code makes the next release :)

**Comment by michaelandrepearce** [comment]
@satishd i think the contributor has gone quiet on this, it is a useful contribution would be a shame not to get this in, i can squash his commits and merge this, we can preserve the authorship, if you're happy with me doing so.

**Comment by satishd** [comment]
>@satishd i think the contributor has gone quiet on this, it is a useful contribution would be a shame not to get this in, i can squash his commits and merge this, we can preserve the authorship, if you're happy with me doing so.

@michaelandrepearce Pl go ahead with that.

**Comment by satishd** [comment]
95bca9732b68ed0954bd3df983b16376987ea1ae is committed with PR #179 by @michaelandrepearce retaining author as @the-ricker .

**Comment by michaelandrepearce** [comment]
@satishd can you check master please, it seems master has been force pushed into by someone (its history has changed) and this squash merge has thus gone.

**Comment by michaelandrepearce** [comment]
@satishd nudge.

**Comment by satishd** [comment]
@michaelandrepearce Can you raise PR with that change?

**Comment by michaelandrepearce** [comment]
@satishd it be good to know what occured with master?

**Comment by satishd** [comment]
@michaelandrepearce Pl dont bother about, I will take care of making these changes and push them in retaining authorship. 

> it be good to know what occured with master?
Right, I will find that out and check any other missing changes. I will also check whether I made any force push.

**Comment by michaelandrepearce** [comment]
@satishd didn't realise github allowed you to re-create deleted branches (nice feature), have re-created the old branch, and re-pushed a new PR.

**Comment by satishd** [comment]
Thanks @michaelandrepearce, merged that into master.

**Pull request closed without merging**
