### PR TITLE
Add BLOB type to schema (Streamline issue 765)

### PR DESCRIPTION
**Pull request by arunmahadevan**
Registry changes for https://github.com/hortonworks/streamline/issues/765

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
What's the use case for this? For Avro,JSON,xml you represent a blob of data as a byte[] typically.

**Comment by michaelandrepearce** [comment]
Eg inputstream is can be turned into a byte array and vice versa

**Comment by HeartSaVioR** [comment]
+1

**Comment by satishd** [comment]
Closes #188

**Pull request merged**
