### PR TITLE
ISSUE-356: Allow merge option only for schemas in enabled state.

### LINKED ISSUE #356: Allow merge option only for schemas in enabled state.
This is deliberately allowed in current master, but it looks confusing to users about merging schema versions in non enabled state.

### PR DESCRIPTION
**Pull request by joylyn**
Contains UI side changes for following
-Fix for #356 
-Also added graphical view for schema branches.

Kindly note this PR should be tested with server side changes before merging.

Closes #356

### CODE REVIEW

**Comment by satishd** [comment]
Thanks @joylyn for raising this PR. 

@joylyn @shahsank3t 
branching UI needs some more changes like dev-1 has a node again for v2 which should not be shown. 
- ignore first version in the non-master branch while showing in the graph. You can directly show the node from master branch.
- better to have respective versions like v2 below the node it self. 
- avoid using grey color for branch lines. 
- have less boundary on branch labels

This can be enhanced later to have better UX. 

screen shot 2018-01-05 at 2 19 38 pm

**Comment by joylyn** [comment]
@satishd 
-We are showing the first version in non-master branch due to following case where the branch is created and a new version is not added to the forked branch. Although the version is same, it is needed to show the branch and its forked version.
schema-branch
-Have removed the grey color for branch lines.
-Due to limitations with the library used for the graph and current time constraints, the below changes will be made post release:
   1. To have respective versions like v2 below the node it self.
   2. to have less boundary on branch labels

**Comment by satishd** [comment]
@joylyn 
>We are showing the first version in non-master branch due to following case where the branch is created and a new version is not added to the forked branch. Although the version is same, it is needed to show the branch and its forked version.

We do not really need to show even when there are no new versions in the forkedout branch as it already shows where it is forkedout from.

You can increase text size of those branches appropriately.

**Comment by joylyn** [comment]
I have updated the PR to not show the first schema version in the forked-out branch.

**Comment by raju-saravanan** [comment]
@joylyn: Can you rebase you PR with the latest master? We fixed a few things in last few days, I want to test those changes against the UI.

**Comment by joylyn** [comment]
@raju-saravanan Rebased with latest master.

**Comment by joylyn** [comment]
Updated the PR to render merge details from "mergeInfo" of schema version.

**Comment by shahsank3t** [comment]
@satishd No, we forgot to add that. I have asked @joylyn to add now to the edges bug fix.

**Comment by joylyn** [comment]
@satishd 
I have fixed the issue now and also showing merge details as seen below
merge-details

**Comment by raju-saravanan** [comment]
@joylyn: I see that if I try to create more than 6 branches and see the graphical representation of schema branch, the UI is not able to render it properly.

screen shot 2018-01-11 at 2 23 13 pm

**Comment by joylyn** [comment]
@raju-saravanan  I have fixed this rendering issue today. Can you check with the latest pull ?

**Comment by raju-saravanan** [comment]
I have tested out the PR again, everything seems to be ok, thanks @joylyn. There are few UI improvements I have in mind, but considering the time constraint, I will raise a separate Github issue for it and you guys can have a look once you have some free cycles.
+1, LGTM.

**Comment by joylyn** [comment]
Rebased with master and resolved conflicts.

**Comment by satishd** [comment]
@joylyn Can you rebase this PR with master as it has conflicts?

**Comment by joylyn** [comment]
@satishd I have resolved the conflicts and rebased with master.

**Comment by joylyn** [comment]
@satishd I missed that issue due to oversight. I have addressed it now.

**Pull request closed without merging**
