### PR TITLE
ISSUE-85 Changed the UI to add schema for better UX experience

### PR DESCRIPTION
**Pull request by satishwaghela**

### CODE REVIEW

**Comment by shahsank3t** [comment]
+1 Looks good. Thanks for the PR @satishwaghela.

**Comment by satishwaghela** [comment]
@satishd I have addressed your comment. please review the changes, thanks

**Comment by harshach** [comment]
@satishwaghela @shahsank3t we need to make Evolve bit more than a check box or at least provide some text what that means. If they uncheck it lets show at the bottom of that check box in orange/yellow color that the new schema versions cannot be added.

**Comment by satishwaghela** [comment]
imgpsh_fullsize 3


@harshach  - I have kept check box as it is and added a message besides when untick as seen in the attached image.
We can either keep checkbox or go with the toggle button saying “Yes / No” but I guess checkbox is sufficient.

**Comment by harshach** [comment]
Thanks @satishwaghela above looks good for evolve. Also it would be good to have option to expand the schema text area.

**Comment by satishwaghela** [comment]
@harshach , I have added expand/collapse button for schema text. please have a look.

**Comment by harshach** [comment]
+1

**Comment by shahsank3t** [comment]
@satishd @harshach I would suggest to merge this PR and continue the discussion on a new issue so at least this new changes gets to the user.

**Comment by satishd** [comment]
Raised issue #100 to discuss on the [comment](https://github.com/hortonworks/registry/pull/86#pullrequestreview-37079969).
@satishwaghela Can you squash these commits? I will merge this PR once that is done.

**Comment by satishwaghela** [comment]
@satishd, I have squashed commits.

**Comment by satishd** [comment]
Thanks @satishwaghela

**Pull request merged**
