### PR TITLE
ISSUE 555 : Expose an option to disable canonical check while adding a new schema version

### PR DESCRIPTION
**Pull request by raju-saravanan**
#555

### CODE REVIEW

**Comment by raju-saravanan** [comment]
@joylyn I merged the changes for UI from HDF3.2 to master. Can you double check if the UI changes all are in place?

**Comment by satishd** [comment]
@raju-saravanan I could not build these changes in my environment. Can you confirm whether you could build this PR in your environment?
@kamalcph Can you also build/verify these changes?

**Comment by raju-saravanan** [comment]
@satishd: I was able to build the PR. @kamalcph and @joylyn Can you guys confirm as well?

**Comment by kamalcph** [comment]
I'm able to build this PR.

**Comment by raju-saravanan** [comment]
@satishd: Please confirm if you are able to build this PR, after your confirmation I will merge this PR.

**Comment by satishd** [comment]
@raju-saravanan I am not able to commit as the permissions seem to be revoked for me. You can merge these changes. 

@vijayk Can you add admin permissions for me on this project as I am a committer on this project? thanks.

**Comment by raju-saravanan** [comment]
@satishd : Will merge the PR.

**Pull request merged**
