### PR TITLE
ISSUE-189 Sanitize mysql create_tables scripts

### PR DESCRIPTION
**Pull request by satishd**

### CODE REVIEW

**Comment by arunmahadevan** [comment]
+1, are there any limits with postgres as well ? as long as its 255 or less we are good.

**Comment by michaelandrepearce** [comment]
should this be possibly pushed into the 0.3.0 RC ?

**Comment by satishd** [comment]
@arunmahadevan 
> +1, are there any limits with postgres as well ? as long as its 255 or less we are good.

- maximum size for a field is 1GB which is again configurable
- One limitation is that indexes can not be created on columns longer than about 2,000 characters.

More details can be found [here](http://wiki.postgresql.org/wiki/FAQ#What_is_the_maximum_size_for_a_row.2C_a_table.2C_and_a_database.3F) , so having 255 is fine and it is consistent.

**Comment by satishd** [comment]
@michaelandrepearce good to be part of 0.3.0 RC.

**Comment by satishd** [comment]
Closes #189

**Pull request merged**
