### PR TITLE
ISSUE-255 Lower logging levels in some of the tests to generate small logs for tests.

### PR DESCRIPTION
**Pull request by satishd**
- Lower logging levels in some of the tests to generate small logs for tests as travis does not allow logs more than 4MB.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Testing github feature... please ignore following comments.

**Comment by HeartSaVioR** [comment]
In current master, `nohup mvn clean install > install-log.log 2>&1 &` creates log file which is 37M.
I'm now build this PR and see how much it will help.

**Comment by HeartSaVioR** [comment]
Even applying the patch, the log file is 26M and line count is 216995. Redirecting log should be necessary, but like Storm we should show log message for failed tests. Otherwise we should change acceptable lowest log level to WARN only for Travis CI build.

**Comment by HeartSaVioR** [comment]
I just found the option `-Dmaven.test.redirectTestOutputToFile=true` which looks similar with what Storm implements `test_runner.clj`, and the log file reduced to 1M while building locally.

I'm building it from my folk with including a failing test. Will put a new pull request if it works properly.
https://travis-ci.org/HeartSaVioR/registry/builds/291480898

**Comment by HeartSaVioR** [comment]
I realized my Travis patch should go along with this patch to reduce the log under 4 MB. I'm merging this locally and apply my patch, and build it from Travis CI.
Build link: https://travis-ci.org/HeartSaVioR/registry/builds/291485991

**Comment by HeartSaVioR** [comment]
Please refer #285.

**Comment by satishd** [comment]
Closing this as these changes are already taken into #285

**Pull request closed without merging**
